<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>

        /* time tutorial 
        // const time = new Date();
        // console.log(typeof time);
        */

        // Async javascript

        /*   this a request to an API

        const getTodos = (callback) => {
            const request = new XMLHttpRequest(); // create request

            request.addEventListener('readystatechange', () => {
                if (request.readyState === 4 && request.status === 200) {
                    const data = JSON.parse(request.responseText);
                    callback(undefined, data);
                } else if (request.readyState === 4) {
                    callback('could not fetch data', undefined);
                }
            });
            request.open('GET', 'https://jsonplaceholder.typicode.com/todos', true); // open request
            // request.open('GET', 'json/todos.json', true); // call a local JSON file
            request.send(); // send request
        }

        console.log(1);
        console.log(2);
        
        getTodos((err, data) => {
            console.log('callback fired');

            if (err) {
                console.log(err);
            } else {
                console.log(data);
            }
        });

        console.log(3);
        console.log(4);

         */
        
        /* this is a request to internal JSON files + callback hell

        const getTodos = (resource, callback) => {

        const request = new XMLHttpRequest();

        request.addEventListener('readystatechange', () => {

        if(request.readyState === 4 && request.status === 200){
            const data = JSON.parse(request.responseText);
            callback(undefined, data);
        } else if (request.readyState === 4){
            callback('could not fetch the data', undefined);
        }

        });

        request.open('GET', resource);
        request.send();

        };

        // this is a callback hell
        // where we have to nest the callback inside the other callback

        getTodos('json/luigi.json', (err, data) => {
        console.log(data);
        getTodos('json/mario.json', (err, data) => {
        console.log(data);
        getTodos('json/shaun.json', (err, data) => {
            console.log(data);
        });
        });
        });

        */
        
        // the problem of a callback is that is messy, hard to read and not maintainable
        // the solution is to use promises

        /* This is a promise 
         const getTodos = (resource) => {

            return new Promise((resolve, reject) => {
                const request = new XMLHttpRequest();

                request.addEventListener('readystatechange', () => {

                    if(request.readyState === 4 && request.status === 200){
                    const data = JSON.parse(request.responseText);
                    resolve(data);
                    } else if (request.readyState === 4){
                    reject('could not fetch the data');
                    }

                });
                
                request.open('GET', resource);
                request.send();
            });

        };

        getTodos('json/luigi.json').then(data => { //.then is used to handle the resolved promise
        console.log('promise resolved:', data);
        }).catch(err => { //.catch is used to handle the rejected promise
        console.log('promise rejected:', err);
        });

        // promise example
        const getSomething = () => {

            return new Promise((resolve, reject) => {
            // do something (fetch data)
            // resolve('some data');
            reject('some error');
            }); // a promise can only be resolved or rejected once

        };

        // getSomething().then(data => {
        //   console.log('promise resolved:', data);
        // }, err => {
        //   console.log('promise rejected:', err);
        // });

        // getSomething().then(data => {
        //   console.log('promise resolved:', data);
        // }).catch(err => {
        //   console.log('promise rejected:', err);
        // });

        */

        /* This is a Chaining promises to resolve the callback hell 

        const getTodos = (resource) => {

            return new Promise((resolve, reject) => {
                const request = new XMLHttpRequest();

                request.addEventListener('readystatechange', () => {

                    if(request.readyState === 4 && request.status === 200){
                    const data = JSON.parse(request.responseText);
                    resolve(data);
                    } else if (request.readyState === 4){
                    reject('could not fetch the data');
                    }

                });
                
                request.open('GET', resource);
                request.send();
            });

        };

        // you can add multiple .then() to a promise
        // this is called chaining promises

        getTodos('json/luigi.json').then(data => {
        console.log('promise 1 resolved:', data);
        return getTodos('json/mario.json');
        }).then(data => {
        console.log('promise 2 resolved:', data);
        return getTodos('json/shaun.json');
        }).then(data => {
        console.log('promise 3 resolved:', data);
        }).catch(err => {
        console.log('promise rejected:', err);
        });

        */

        /* Fetch API -> easier and cleaner way to deal with the request 

        // fetch API -> it is a modern way to make requests to an API and it requires less code than XMLHttpRequest
        // and it also gonna implement the promise API under the hood

        fetch('json/luigi.json').then(response => {
            //console.log(response);
            return response.json(); //.json() will return a promise and it will resolve with the data
            }).then(data => {
                console.log(data);
            }).catch(err => {
                console.log(err); // the promise will be only ever rejected if the network request failed
                // if you mistype the file name, the promise will not be resolved and it will respond with the catch block.
            });

        */

        /* Async & Await -> modern way to handle promises - IMPORTANT 

        const getTodos = async () => {

            let response = await fetch('json/luigi.json'); // this will return a promise 
            // and await will stop the code until the promise is resolved and then it will asign the value to the variable
            let data = await response.json();

            let response1 = await fetch('json/mario.json');
            let data1 = await response1.json();
            return { data, data1 };

        };

        console.log(1);
        console.log(2);

        getTodos().then(({ data, data1 }) => console.log('resolved:', data, data1));
        // whenever you call a async function, it will always return a promise. regardless of what you return from the function


        console.log(3);
        console.log(4);

        // console.log(getTodos());

        */

        /* Error handling with async & await 

        
        const getTodos = async () => {

        let response = await fetch('json/luigi.json');

        // the if statement is used to handle an error if the fetch request fails

        if(response.status !== 200){
        throw new Error('cannot fetch the data'); // throw is used to reject the promise
        }

        let data = await response.json();
        return data;

        };

        getTodos()
        .then(data => console.log('resolved:', data))
        .catch(err => console.log('rejected:', err.message));

        */


    </script>
</body>
</html>